export const CREATE_QUESTION = "CREATE_QUESTION";
export const RETRIEVE_QUESTIONS = "RETRIEVE_QUESTIONS";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_ALL_QUESTIONS = "DELETE_ALL_QUESTIONS";