export const CREATE_QUESTION = "CREATE_QUESTION";
export const RETRIEVE_QUESTIONS = "RETRIEVE_QUESTIONS";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_ALL_QUESTIONS = "DELETE_ALL_QUESTIONS";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_ALL_CATEGORIES = "DELETE_ALL_CATEGORIES";